###################################################################################################

- name: consul

  hosts: consul

  become: true

  roles:

    - role: consul

  tags:
    - brain
    - consul

###################################################################################################
