###################################################################################################

- name: consul

  hosts: consul-nodes

  sudo: true

  roles:

    - role: consul

  tags:
    - brain
    - consul

###################################################################################################
