###################################################################################################

- name: consul | ping

  hosts: consul-nodes

  gather_facts: false

  roles:

    - role: artemis/platform/ping

  tags:
    - database
    - consul

###################################################################################################

- name: consul

  hosts: consul-nodes

  sudo: true

  vars :

     btrfs_label: '{{ home_name   }}'
     btrfs_mount: '{{ home_base   }}'

     user_base  : '{{ btrfs_mount }}'

  roles:

    - role: artemis/platform/server

    - role: database/consul

    - { role: artemis/process-control/systemd,
       systemd_name    : '{{ consul_service_name    }}' ,
       systemd_run_as  : '{{ consul_service_run_as  }}' ,
       systemd_command : '{{ consul_service_command }}' ,
       systemd_state   : '{{ consul_service_state   }}' }

    - role: artemis/platform/terminus

  tags:
    - database
    - consul

###################################################################################################
